algorithm : dreamer-v1
operation :
    save : False
    log_dir : cheetah-run
    device : cuda
environment :
    benchmark : dmc
    domain_name : cheetah
    task_name : run
    seed : 0
    visualize_reward : False
    from_pixels : False
    height : 64
    width : 64
    frame_skip : 2
    pixel_norm : False
    
parameters :
    dreamer :
        train_iterations : 1000
        horizon_length : 15
        batch_size : 50
        batch_length : 50
        collect_interval : 1
        num_interaction_episodes : 1
        seed_episodes : 5
        num_evaluate : 3
        
        kl_divergence_scale : 1
        free_nats : 3
        discount : 0.99
        lambda_ : 0.95
        
        use_continue_flag : False
        use_classifier : False
        actor_learning_rate : 0.00008
        critic_learning_rate : 0.00008
        model_learning_rate : 0.0008
        grad_norm_type : 2
        clip_grad : 100
        
        deterministic_size : 256
        stochastic_size : 17
        embedded_state_size : 17
        buffer :
            capacity : 500000
        
        encoder : 
            hidden_size : 128
            num_layers : 2
            activation : ReLU

        decoder : 
            hidden_size : 128
            num_layers : 3
            activation : ReLU

        rssm :
            recurrent_model : 
                hidden_size : 128
                activation : ELU

            transition_model : 
                hidden_size : 128
                num_layers : 3
                activation : ELU
                min_std : 0.1

            representation_model:
                hidden_size : 128
                num_layers : 3
                activation : ELU
                min_std : 0.1
            
        reward :
            hidden_size : 128
            num_layers : 3
            activation : ELU

        continue_ :
            hidden_size : 400
            num_layers : 3
            activation : ELU
        
        agent :
            actor :
                hidden_size : 400
                min_std : 0.0001
                init_std : 5.
                mean_scale : 5
                activation : ELU
                num_layers : 5

            critic : 
                hidden_size : 400
                activation : ELU
                num_layers : 5 